baseURL = "https://example.org/"
DefaultContentLanguage = "en"
title = "ilmerkul"
theme = "PaperMod"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = true
enableRobotsTXT = true

staticDir = ["static"]

[params]
    env = "production"
    description = "My private blog"
    author = "Ilya Merkulov"
    defaultTheme = "auto"
    ShowShareButtons = true
    ShowReadingTime = true
    ShowToc = false
    ShowPostNavLinks = true
    ShowCodeCopyButtons = true
    ShowRssButtonInSectionTermList = true
    images = [ "images/avatar-favicon.jpg" ]
    params.mainSections = ["post"]

[params.profileMode]
    enabled = false

[params.homeInfoParams]
    Title = "Welcome to my Blog!"
    Content = """Welcome to my blog!

I'm a Russian Data Scientist and student MSU.

My blog contains the context about everything.

About any questions related to this blog you can contact me via email: merkuloviv@my.msu.ru
  """

[[params.socialIcons]]
    name = "github"
    title = "My GitHub profile"
    url = "https://github.com/ilmerkul"

[[params.socialIcons]]
    name = "email"
    title = "Contact me via email"
    url = "mailto:merkuloviv@my.msu.ru"

[params.assets]
    favicon = "images/fav/favicon.ico"
    favicon16x16 = "images/fav/favicon-16x16.png"
    favicon32x32 = "images/fav/favicon-32x32.png"
    apple_touch_icon = "images/fav/apple-touch-icon.png"
    android-chrome-192x192 = "images/fav/android-chrome-192x192.png"
    android-chrome-512x512 = "images/fav/android-chrome-512x512.png"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[[menu.main]]
    name = "CV"
    url = "page/cv/"
    weight = 3
